<?php
/**
 * insert_furniture.php - Staff Insert Furniture Page
 * Allows staff to add new furniture products with material requirements
 * Furniture ID is auto-generated by the system
 */

require_once '../inc/config.php';
require_once '../inc/session.php';
require_once '../inc/functions.php';

// Check if user is logged in as staff
checkStaffRole();

$message = '';
$messageType = '';
$newFurnitureId = null;

// Get all materials for selection
$materials = getAllMaterials($conn);

// Handle form submission
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $furnitureName = sanitizeInput($_POST['furniture_name'] ?? '');
    $furnitureDescription = sanitizeInput($_POST['furniture_description'] ?? '');
    $price = (float)($_POST['price'] ?? 0);
    $stockQuantity = (int)($_POST['stock_quantity'] ?? 0);
    $category = sanitizeInput($_POST['category'] ?? '');
    
    // Get selected materials
    $selectedMaterials = [];
    if (isset($_POST['materials']) && is_array($_POST['materials'])) {
        foreach ($_POST['materials'] as $materialId => $materialData) {
            if (isset($materialData['quantity']) && $materialData['quantity'] > 0) {
                $selectedMaterials[] = [
                    'id' => (int)$materialId,
                    'quantity' => (float)$materialData['quantity']
                ];
            }
        }
    }
    
    $errors = [];
    
    // Validate inputs
    if (empty($furnitureName)) {
        $errors[] = 'Furniture name is required.';
    } elseif (strlen($furnitureName) < 2) {
        $errors[] = 'Furniture name must be at least 2 characters.';
    }
    
    if (empty($furnitureDescription)) {
        $errors[] = 'Furniture description is required.';
    } elseif (strlen($furnitureDescription) < 10) {
        $errors[] = 'Please provide a more detailed description (at least 10 characters).';
    }
    
    if ($price <= 0) {
        $errors[] = 'Price must be greater than 0.';
    }
    
    if ($stockQuantity < 0) {
        $errors[] = 'Stock quantity cannot be negative.';
    }
    
    if (empty($category)) {
        $errors[] = 'Category is required.';
    }
    
    if (empty($selectedMaterials)) {
        $errors[] = 'At least one material is required for this furniture product.';
    }
    
    // Handle image upload
    $imageFile = $_FILES['furniture_image'] ?? null;
    if (!$imageFile || $imageFile['error'] !== UPLOAD_ERR_OK) {
        $errors[] = 'Furniture image is required.';
    } else {
        $allowedTypes = ['image/jpeg', 'image/png', 'image/gif', 'image/webp'];
        if (!in_array($imageFile['type'], $allowedTypes)) {
            $errors[] = 'Only JPG, PNG, GIF, and WEBP images are allowed.';
        }
        if ($imageFile['size'] > MAX_FILE_SIZE) {
            $errors[] = 'Image size must be less than 2MB.';
        }
    }
    
    // Handle view images (additional product views)
    $viewImages = $_FILES['view_images'] ?? [];
    $uploadedViews = [];

    if (empty($errors)) {
        $result = insertFurniture($conn, [
            'furniture_name' => $furnitureName,
            'furniture_description' => $furnitureDescription,
            'price' => $price,
            'stock_quantity' => $stockQuantity,
            'category' => $category,
            'materials' => $selectedMaterials
        ], $imageFile);

        if ($result['success']) {
            $newFurnitureId = $result['furniture_id'];

            // Process additional view images
            if (!empty($viewImages['name']) && is_array($viewImages['name'])) {
                $viewEntries = [];
                for ($i = 0; $i < count($viewImages['name']); $i++) {
                    if ($viewImages['error'][$i] === UPLOAD_ERR_OK && !empty($viewImages['name'][$i])) {
                        $ext = pathinfo($viewImages['name'][$i], PATHINFO_EXTENSION);
                        $viewName = time() . '_view' . ($i + 1) . '_' . uniqid() . '.' . $ext;
                        $dest = FURNITURE_IMAGE_UPLOAD_PATH . $viewName;
                        if (move_uploaded_file($viewImages['tmp_name'][$i], $dest)) {
                            $viewEntries[] = [
                                'path' => $viewName,
                                'sort_order' => count($viewEntries) + 2, // main img is sort 1
                                'is_primary' => 0
                            ];
                        }
                    }
                }
                if (!empty($viewEntries)) {
                    insertFurnitureImages($conn, $newFurnitureId, $viewEntries);
                }
            }

            // Save customization options
            $customCount = 0;
            if ($newFurnitureId) {
                $colorEntries = [];
                if (!empty($_POST['colors']['name'])) {
                    foreach ($_POST['colors']['name'] as $i => $cname) {
                        if (!empty(trim($cname))) {
                            $colorEntries[] = [
                                'name' => trim($cname),
                                'hex' => trim($_POST['colors']['hex'][$i] ?? '#cccccc'),
                                'additional_price' => floatval($_POST['colors']['price'][$i] ?? 0),
                                'sort_order' => count($colorEntries) + 1
                            ];
                        }
                    }
                }
                if (!empty($colorEntries)) { insertFurnitureColors($conn, $newFurnitureId, $colorEntries); $customCount += count($colorEntries); }

                $sizeEntries = [];
                if (!empty($_POST['sizes']['name'])) {
                    foreach ($_POST['sizes']['name'] as $i => $sname) {
                        if (!empty(trim($sname))) {
                            $sizeEntries[] = [
                                'name' => trim($sname),
                                'dimensions' => trim($_POST['sizes']['dim'][$i] ?? ''),
                                'additional_price' => floatval($_POST['sizes']['price'][$i] ?? 0),
                                'sort_order' => count($sizeEntries) + 1
                            ];
                        }
                    }
                }
                if (!empty($sizeEntries)) { insertFurnitureSizes($conn, $newFurnitureId, $sizeEntries); $customCount += count($sizeEntries); }

                $accEntries = [];
                if (!empty($_POST['accessories']['name'])) {
                    foreach ($_POST['accessories']['name'] as $i => $aname) {
                        if (!empty(trim($aname))) {
                            $accEntries[] = [
                                'name' => trim($aname),
                                'description' => trim($_POST['accessories']['desc'][$i] ?? ''),
                                'additional_price' => floatval($_POST['accessories']['price'][$i] ?? 0),
                                'sort_order' => count($accEntries) + 1
                            ];
                        }
                    }
                }
                if (!empty($accEntries)) { insertFurnitureAccessories($conn, $newFurnitureId, $accEntries); $customCount += count($accEntries); }
            }

            $message = $result['message'] . (!empty($viewEntries) ? ' (' . count($viewEntries) . ' additional views saved.)' : '') . ($customCount > 0 ? ' (' . $customCount . ' customization options saved.)' : '');
            $messageType = 'success';

            // Clear form
            $_POST = [];
        } else {
            $message = $result['message'];
            $messageType = 'danger';
        }
    } else {
        $message = implode('<br>', $errors);
        $messageType = 'danger';
    }
}

// Get all furniture for display
$allFurniture = getAllFurniture($conn);

// Fetch product view images for the list
$listImages = [];
$imgSql = "SELECT FurnitureID, ImagePath, IsPrimary FROM FurnitureImage ORDER BY SortOrder ASC";
$imgResult = mysqli_query($conn, $imgSql);
while ($img = mysqli_fetch_assoc($imgResult)) {
    if (!isset($listImages[$img['FurnitureID']])) {
        $listImages[$img['FurnitureID']] = [];
    }
    $listImages[$img['FurnitureID']][] = $img;
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Insert Furniture - Staff Panel</title>
    <link rel="stylesheet" href="../assets/css/style.css">
</head>
<body>
    <header class="header">
        <div class="container">
            <a href="../index.php" style="text-decoration:none;">
            <div class="logo">
                <h1>Premium Living Furniture</h1>
                <p>Staff Management Portal</p>
            </div>
            </a>
            <div class="user-info">
    <span>👔 Welcome, <?php echo htmlspecialchars($_SESSION['user_name']); ?> (Staff)</span>
    <div class="header-buttons">
        <a href="../index.php" class="btn-dashboard">🏠 Back to Home</a>
        <a href="dashboard.php" class="btn-dashboard">📊 Dashboard</a>
        <a href="logout.php" class="btn-logout">🚪 Logout</a>
    </div>
</div>
        </div>
    </header>

    <div class="container">
        <div class="dashboard-layout">
            <!-- Sidebar Navigation -->
            <aside class="sidebar">
                <h3>Staff Menu</h3>
                <ul>
                    <li><a href="dashboard.php">📊 Dashboard</a></li>
                    <li><a href="insert_furniture.php" class="active">➕ Insert Furniture</a></li>
                    <li><a href="update_furniture.php">✏️ Update Furniture</a></li>
                    <li><a href="insert_material.php">📦 Insert Material</a></li>
                    <li><a href="update_material.php">✏️ Update Material</a></li>
                    <li><a href="manage_customers.php">👥 Manage Customers</a></li>
                    <li><a href="register_customer.php">👤 Register Customer</a></li>
                    <li><a href="manage_orders.php">📋 Manage Orders</a></li>
                    <li><a href="manage_inquiries.php">📬 Inquiries</a></li>
                    <li><a href="register_staff.php">👔 Register Staff</a></li>
                    <li><a href="analytics.php">📊 Analytics</a></li>
                    <li><a href="generate_report.php">📈 Generate Report</a></li>
                    <li><a href="delete_material.php">🗑️ Delete Material</a></li>
                    <li><a href="delete_furniture.php">🗑️ Delete Furniture</a></li>
                </ul>
            </aside>

            <!-- Main Content -->
            <main class="main-content">
                <h2>Insert New Furniture Product</h2>
                <p>Add a new furniture product. Furniture ID will be automatically generated.</p>
                
                <?php if ($message): ?>
                    <div class="alert alert-<?php echo $messageType; ?>">
                        <?php echo $message; ?>
                    </div>
                <?php endif; ?>
                
                <!-- Insert Form -->
                <form method="POST" action="" enctype="multipart/form-data" data-validate>
                    <div class="form-row">
                        <div class="form-group">
                            <label for="furniture_name" class="required">Furniture Name</label>
                            <input type="text" name="furniture_name" id="furniture_name" 
                                   class="form-control"
                                   required
                                   minlength="2"
                                   maxlength="100"
                                   value="<?php echo htmlspecialchars($_POST['furniture_name'] ?? ''); ?>"
                                   placeholder="e.g., Executive Oak Desk">
                            <div class="invalid-feedback" id="furniture_name_error"></div>
                        </div>
                        
                        <div class="form-group">
                            <label for="category" class="required">Category</label>
                            <select name="category" id="category" class="form-control" required>
                                <option value="">Select Category</option>
                                <option value="Desks" <?php echo (($_POST['category'] ?? '') == 'Desks') ? 'selected' : ''; ?>>Desks</option>
                                <option value="Chairs" <?php echo (($_POST['category'] ?? '') == 'Chairs') ? 'selected' : ''; ?>>Chairs</option>
                                <option value="Tables" <?php echo (($_POST['category'] ?? '') == 'Tables') ? 'selected' : ''; ?>>Tables</option>
                                <option value="Sofas" <?php echo (($_POST['category'] ?? '') == 'Sofas') ? 'selected' : ''; ?>>Sofas</option>
                                <option value="Storage" <?php echo (($_POST['category'] ?? '') == 'Storage') ? 'selected' : ''; ?>>Storage</option>
                                <option value="Beds" <?php echo (($_POST['category'] ?? '') == 'Beds') ? 'selected' : ''; ?>>Beds</option>
                            </select>
                            <div class="invalid-feedback" id="category_error"></div>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label for="furniture_description" class="required">Description</label>
                        <textarea name="furniture_description" id="furniture_description" 
                                  class="form-control"
                                  required
                                  minlength="10"
                                  maxlength="1000"
                                  rows="4"
                                  placeholder="Detailed description of the furniture product"><?php echo htmlspecialchars($_POST['furniture_description'] ?? ''); ?></textarea>
                        <div class="invalid-feedback" id="furniture_description_error"></div>
                    </div>
                    
                    <div class="form-row">
                        <div class="form-group">
                            <label for="price" class="required">Price ($)</label>
                            <input type="number" name="price" id="price" 
                                   class="form-control"
                                   data-type="number"
                                   required
                                   min="0.01"
                                   step="0.01"
                                   value="<?php echo htmlspecialchars($_POST['price'] ?? ''); ?>"
                                   placeholder="0.00">
                            <div class="invalid-feedback" id="price_error"></div>
                        </div>
                        
                        <div class="form-group">
                            <label for="stock_quantity">Initial Stock Quantity</label>
                            <input type="number" name="stock_quantity" id="stock_quantity" 
                                   class="form-control"
                                   data-type="number"
                                   min="0"
                                   step="1"
                                   value="<?php echo htmlspecialchars($_POST['stock_quantity'] ?? '0'); ?>">
                            <div class="invalid-feedback" id="stock_quantity_error"></div>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <label for="furniture_image" class="required">Primary Furniture Image</label>
                        <input type="file" name="furniture_image" id="furniture_image"
                               class="form-control"
                               accept="image/jpeg,image/png,image/gif,image/webp"
                               data-preview="image_preview"
                               required>
                        <div id="image_preview_container" style="margin-top: var(--spacing-sm);">
                            <img id="image_preview" style="max-width: 200px; display: none; border-radius: 8px;">
                        </div>
                        <small>Accepted formats: JPG, PNG, GIF, WEBP. Max size: 2MB</small>
                        <div class="invalid-feedback" id="furniture_image_error"></div>
                    </div>

                    <div class="form-group">
                        <label>Additional Product Views <small>(optional, up to 4)</small></label>
                        <p style="font-size: 0.85rem; color: var(--gray-500); margin-bottom: var(--space-2);">
                            📸 Upload additional angles/views of the product for the gallery.
                        </p>
                        <div id="view-images-container">
                            <div class="view-image-row" style="display:flex;align-items:center;gap:var(--space-3);margin-bottom:var(--space-2);">
                                <input type="file" name="view_images[]"
                                       class="form-control"
                                       accept="image/jpeg,image/png,image/gif,image/webp"
                                       style="flex:1;"
                                       onchange="previewViewImage(this, 0)">
                                <img class="view-preview" style="width:48px;height:48px;object-fit:cover;border-radius:6px;display:none;border:1px solid var(--gray-300);">
                            </div>
                            <div class="view-image-row" style="display:flex;align-items:center;gap:var(--space-3);margin-bottom:var(--space-2);">
                                <input type="file" name="view_images[]"
                                       class="form-control"
                                       accept="image/jpeg,image/png,image/gif,image/webp"
                                       style="flex:1;"
                                       onchange="previewViewImage(this, 1)">
                                <img class="view-preview" style="width:48px;height:48px;object-fit:cover;border-radius:6px;display:none;border:1px solid var(--gray-300);">
                            </div>
                            <div class="view-image-row" style="display:flex;align-items:center;gap:var(--space-3);margin-bottom:var(--space-2);">
                                <input type="file" name="view_images[]"
                                       class="form-control"
                                       accept="image/jpeg,image/png,image/gif,image/webp"
                                       style="flex:1;"
                                       onchange="previewViewImage(this, 2)">
                                <img class="view-preview" style="width:48px;height:48px;object-fit:cover;border-radius:6px;display:none;border:1px solid var(--gray-300);">
                            </div>
                            <div class="view-image-row" style="display:flex;align-items:center;gap:var(--space-3);margin-bottom:var(--space-2);">
                                <input type="file" name="view_images[]"
                                       class="form-control"
                                       accept="image/jpeg,image/png,image/gif,image/webp"
                                       style="flex:1;"
                                       onchange="previewViewImage(this, 3)">
                                <img class="view-preview" style="width:48px;height:48px;object-fit:cover;border-radius:6px;display:none;border:1px solid var(--gray-300);">
                            </div>
                        </div>
                        <small>Each file max 2MB. These show as gallery thumbnails on the product page.</small>
                    </div>
                    
                    <h3 style="margin-top: var(--spacing-xl);">Materials Required</h3>
                    <p>Select the materials needed to produce this furniture product.</p>
                    
                    <div class="table-container">
                        <table class="materials-table">
                            <thead>
                                <tr>
                                    <th>Select</th>
                                    <th>Material Name</th>
                                    <th>Available Quantity</th>
                                    <th>Unit</th>
                                    <th>Quantity Required per Unit</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($materials as $material): ?>
                                    <tr>
                                        <td style="text-align: center;">
                                            <input type="checkbox" name="materials[<?php echo $material['MaterialID']; ?>][selected]" 
                                                   class="material-checkbox"
                                                   data-material-id="<?php echo $material['MaterialID']; ?>"
                                                   onchange="toggleMaterialInput(<?php echo $material['MaterialID']; ?>, this.checked)">
                                        </td>
                                        <td><?php echo htmlspecialchars($material['MaterialName']); ?></td>
                                        <td><?php echo number_format($material['PhysicalQuantity'], 2); ?></td>
                                        <td><?php echo htmlspecialchars($material['Unit']); ?></td>
                                        <td>
                                            <input type="hidden" name="materials[<?php echo $material['MaterialID']; ?>][selected]" value="0">
                                            <input type="number" name="materials[<?php echo $material['MaterialID']; ?>][quantity]" 
                                                   id="material_quantity_<?php echo $material['MaterialID']; ?>"
                                                   class="form-control material-quantity"
                                                   style="width: 120px;"
                                                   min="0.01"
                                                   step="0.01"
                                                   placeholder="Quantity"
                                                   disabled>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                    
                    <!-- Customization Options -->
                    <h3 style="margin-top:var(--spacing-xl);">🎨 Customization Options <small>(optional)</small></h3>
                    <p style="margin-bottom:var(--space-4);">Define available colors, sizes, and accessories for this product. These can be managed later from Update Furniture.</p>

                    <div class="form-row" style="gap:var(--space-6);">
                        <!-- Colors -->
                        <div class="form-group" style="flex:1;">
                            <label><strong>🎨 Colors</strong></label>
                            <div id="colors-container">
                                <div class="custom-row" style="display:flex;gap:6px;margin-bottom:4px;">
                                    <input type="text" name="colors[name][]" placeholder="Color name" class="form-control" style="flex:2;">
                                    <input type="text" name="colors[hex][]" placeholder="#hex" class="form-control" style="flex:1;max-width:90px;">
                                    <input type="number" name="colors[price][]" placeholder="+$" class="form-control" style="flex:1;max-width:70px;" step="0.01" min="0" value="0">
                                </div>
                            </div>
                            <button type="button" class="btn btn-sm btn-outline" onclick="addCustomRow('colors-container', 'color')" style="font-size:0.8rem;">+ Add Color</button>
                        </div>

                        <!-- Sizes -->
                        <div class="form-group" style="flex:1;">
                            <label><strong>📏 Sizes</strong></label>
                            <div id="sizes-container">
                                <div class="custom-row" style="display:flex;gap:6px;margin-bottom:4px;">
                                    <input type="text" name="sizes[name][]" placeholder="Size name" class="form-control" style="flex:2;">
                                    <input type="text" name="sizes[dim][]" placeholder="Dimensions" class="form-control" style="flex:2;">
                                    <input type="number" name="sizes[price][]" placeholder="+$" class="form-control" style="flex:1;max-width:70px;" step="0.01" min="0" value="0">
                                </div>
                            </div>
                            <button type="button" class="btn btn-sm btn-outline" onclick="addCustomRow('sizes-container', 'size')" style="font-size:0.8rem;">+ Add Size</button>
                        </div>
                    </div>

                    <!-- Accessories -->
                    <div class="form-group">
                        <label><strong>🔧 Accessories</strong></label>
                        <div id="accessories-container">
                            <div class="custom-row" style="display:flex;gap:6px;margin-bottom:4px;align-items:center;">
                                <input type="text" name="accessories[name][]" placeholder="Accessory name" class="form-control" style="flex:2;">
                                <input type="text" name="accessories[desc][]" placeholder="Description" class="form-control" style="flex:3;">
                                <input type="number" name="accessories[price][]" placeholder="+$" class="form-control" style="flex:1;max-width:70px;" step="0.01" min="0" value="0">
                            </div>
                        </div>
                        <button type="button" class="btn btn-sm btn-outline" onclick="addCustomRow('accessories-container', 'accessory')" style="font-size:0.8rem;">+ Add Accessory</button>
                    </div>

                    <div class="form-group" style="margin-top: var(--spacing-xl);">
                        <button type="submit" class="btn btn-primary">➕ Add Furniture Product</button>
                        <button type="reset" class="btn btn-secondary">Clear Form</button>
                    </div>
                </form>
                
                <hr style="margin: var(--spacing-xl) 0;">
                
                <!-- Existing Furniture List -->
                <h3>Existing Furniture Products</h3>
                <?php if (empty($allFurniture)): ?>
                    <div class="alert alert-info">No furniture products found.</div>
                <?php else: ?>
                    <div class="table-container">
                        <table data-sortable>
                            <thead>
                                <tr>
                                    <th class="sortable">ID</th>
                                    <th>Image</th>
                                    <th class="sortable">Name</th>
                                    <th class="sortable">Category</th>
                                    <th class="sortable">Price</th>
                                    <th class="sortable">Stock</th>
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($allFurniture as $furniture):
                                    $pid = $furniture['FurnitureID'];
                                    $views = $listImages[$pid] ?? [];
                                    $pri = null;
                                    foreach ($views as $v) { if ($v['IsPrimary']) { $pri = $v; break; } }
                                    if (!$pri && !empty($views)) $pri = $views[0];
                                    $listImgSrc = $pri
                                        ? '../assets/images/furniture/' . str_replace(' ', '%20', $pri['ImagePath'])
                                        : '../assets/images/furniture/' . htmlspecialchars($furniture['FurnitureImage']);
                                ?>
                                    <tr>
                                        <td><?php echo $furniture['FurnitureID']; ?></td>
                                        <td>
                                            <img src="<?php echo $listImgSrc; ?>"
                                                 style="width: 50px; height: 50px; object-fit: cover; border-radius: 5px;"
                                                 onerror="this.src='../assets/images/furniture/placeholder.jpg'">
                                        </td>
                                        <td><?php echo htmlspecialchars($furniture['FurnitureName']); ?></td>
                                        <td><?php echo htmlspecialchars($furniture['Category']); ?></td>
                                        <td><?php echo formatCurrency($furniture['Price']); ?></td>
                                        <td><?php echo $furniture['StockQuantity']; ?></td>
                                        <td>
                                            <?php if ($furniture['is_sold_out']): ?>
                                                <span class="badge badge-danger">Sold Out</span>
                                            <?php elseif ($furniture['StockQuantity'] < 5): ?>
                                                <span class="badge badge-warning">Low Stock</span>
                                            <?php else: ?>
                                                <span class="badge badge-success">In Stock</span>
                                            <?php endif; ?>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                <?php endif; ?>
            </main>
        </div>
    </div>

    <footer class="footer">
        <div class="container">
            <p>&copy; 2025 Premium Living Furniture Co. Ltd. All rights reserved.</p>
        </div>
    </footer>

    <script src="../assets/js/validation.js"></script>
    <script>
        function toggleMaterialInput(materialId, isChecked) {
            const quantityInput = document.getElementById(`material_quantity_${materialId}`);
            if (quantityInput) {
                quantityInput.disabled = !isChecked;
                if (!isChecked) {
                    quantityInput.value = '';
                }
            }
        }
        
        // Image preview
        document.getElementById('furniture_image')?.addEventListener('change', function(e) {
            const file = e.target.files[0];
            const preview = document.getElementById('image_preview');
            if (file && preview) {
                const reader = new FileReader();
                reader.onload = function(event) {
                    preview.src = event.target.result;
                    preview.style.display = 'block';
                };
                reader.readAsDataURL(file);
            }
        });

        // View image previews
        function previewViewImage(input, index) {
            const row = input.closest('.view-image-row');
            const preview = row ? row.querySelector('.view-preview') : null;
            if (input.files && input.files[0] && preview) {
                const reader = new FileReader();
                reader.onload = function(e) {
                    preview.src = e.target.result;
                    preview.style.display = 'block';
                };
                reader.readAsDataURL(input.files[0]);
            }
        }

        // Add customization row
        function addCustomRow(containerId, type) {
            const container = document.getElementById(containerId);
            if (!container) return;
            const div = document.createElement('div');
            div.className = 'custom-row';
            div.style.cssText = 'display:flex;gap:6px;margin-bottom:4px;';
            let inputs = '';
            if (type === 'color') {
                inputs = '<input type=\"text\" name=\"colors[name][]\" placeholder=\"Color name\" class=\"form-control\" style=\"flex:2;\">' +
                    '<input type=\"text\" name=\"colors[hex][]\" placeholder=\"#hex\" class=\"form-control\" style=\"flex:1;max-width:90px;\">' +
                    '<input type=\"number\" name=\"colors[price][]\" placeholder=\"+$\" class=\"form-control\" style=\"flex:1;max-width:70px;\" step=\"0.01\" min=\"0\" value=\"0\">';
            } else if (type === 'size') {
                inputs = '<input type=\"text\" name=\"sizes[name][]\" placeholder=\"Size name\" class=\"form-control\" style=\"flex:2;\">' +
                    '<input type=\"text\" name=\"sizes[dim][]\" placeholder=\"Dimensions\" class=\"form-control\" style=\"flex:2;\">' +
                    '<input type=\"number\" name=\"sizes[price][]\" placeholder=\"+$\" class=\"form-control\" style=\"flex:1;max-width:70px;\" step=\"0.01\" min=\"0\" value=\"0\">';
            } else if (type === 'accessory') {
                inputs = '<input type=\"text\" name=\"accessories[name][]\" placeholder=\"Name\" class=\"form-control\" style=\"flex:2;\">' +
                    '<input type=\"text\" name=\"accessories[desc][]\" placeholder=\"Description\" class=\"form-control\" style=\"flex:3;\">' +
                    '<input type=\"number\" name=\"accessories[price][]\" placeholder=\"+$\" class=\"form-control\" style=\"flex:1;max-width:70px;\" step=\"0.01\" min=\"0\" value=\"0\">';
            }
            div.innerHTML = inputs + '<button type=\"button\" onclick=\"this.parentElement.remove()\" style=\"background:none;border:none;color:var(--danger);cursor:pointer;font-size:1.1rem;padding:0 4px;\" title=\"Remove\">✕</button>';
            container.appendChild(div);
        }
    </script>
</body>
</html>