<?php
/**
 * insert_material.php - Staff Insert Material Page
 * Allows staff to add new materials to the inventory
 * Material ID is auto-generated by the system
 */

require_once '../inc/config.php';
require_once '../inc/session.php';
require_once '../inc/functions.php';

// Check if user is logged in as staff
checkStaffRole();

$message = '';
$messageType = '';
$newMaterialId = null;

// Handle form submission
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $materialName = sanitizeInput($_POST['material_name'] ?? '');
    $physicalQuantity = (float)($_POST['physical_quantity'] ?? 0);
    $unit = sanitizeInput($_POST['unit'] ?? '');
    $reorderLevel = (float)($_POST['reorder_level'] ?? 0);
    
    $errors = [];
    
    // Validate inputs
    if (empty($materialName)) {
        $errors[] = 'Material name is required.';
    } elseif (strlen($materialName) < 2) {
        $errors[] = 'Material name must be at least 2 characters.';
    }
    
    if ($physicalQuantity <= 0) {
        $errors[] = 'Physical quantity must be greater than 0.';
    }
    
    if (empty($unit)) {
        $errors[] = 'Unit is required.';
    }
    
    if ($reorderLevel < 0) {
        $errors[] = 'Reorder level cannot be negative.';
    }
    
    if (empty($errors)) {
        $result = insertMaterial($conn, [
            'material_name' => $materialName,
            'physical_quantity' => $physicalQuantity,
            'unit' => $unit,
            'reorder_level' => $reorderLevel
        ]);
        
        if ($result['success']) {
            $message = $result['message'];
            $messageType = 'success';
            $newMaterialId = $result['material_id'];
            
            // Clear form
            $_POST = [];
        } else {
            $message = $result['message'];
            $messageType = 'danger';
        }
    } else {
        $message = implode('<br>', $errors);
        $messageType = 'danger';
    }
}

// Get all materials for display
$materials = getAllMaterials($conn);
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Insert Material - Staff Panel</title>
    <link rel="stylesheet" href="../assets/css/style.css">
</head>
<body>
    <header class="header">
        <div class="container">
            <a href="../index.php" style="text-decoration:none;">
            <div class="logo">
                <h1>Premium Living Furniture</h1>
                <p>Staff Management Portal</p>
            </div>
            </a>
            <div class="user-info">
    <span>👔 Welcome, <?php echo htmlspecialchars($_SESSION['user_name']); ?> (Staff)</span>
    <div class="header-buttons">
        <a href="../index.php" class="btn-dashboard">🏠 Back to Home</a>
        <a href="dashboard.php" class="btn-dashboard">📊 Dashboard</a>
        <a href="logout.php" class="btn-logout">🚪 Logout</a>
    </div>
</div>
        </div>
    </header>

    <div class="container">
        <div class="dashboard-layout">
            <!-- Sidebar Navigation -->
            <aside class="sidebar">
                <h3>Staff Menu</h3>
                <ul>
                    <li><a href="dashboard.php">📊 Dashboard</a></li>
                    <li><a href="insert_furniture.php">➕ Insert Furniture</a></li>
                    <li><a href="update_furniture.php">✏️ Update Furniture</a></li>
                    <li><a href="insert_material.php" class="active">📦 Insert Material</a></li>
                    <li><a href="update_material.php">✏️ Update Material</a></li>
                    <li><a href="manage_customers.php">👥 Manage Customers</a></li>
                    <li><a href="register_customer.php">👤 Register Customer</a></li>
                    <li><a href="manage_orders.php">📋 Manage Orders</a></li>
                    <li><a href="manage_inquiries.php">📬 Inquiries</a></li>
                    <li><a href="register_staff.php">👔 Register Staff</a></li>
                    <li><a href="analytics.php">📊 Analytics</a></li>
                    <li><a href="generate_report.php">📈 Generate Report</a></li>
                    <li><a href="delete_material.php">🗑️ Delete Material</a></li>
                    <li><a href="delete_furniture.php">🗑️ Delete Furniture</a></li>
                </ul>
            </aside>

            <!-- Main Content -->
            <main class="main-content">
                <h2>Insert New Material</h2>
                <p>Add a new material to the inventory. Material ID will be automatically generated.</p>
                
                <?php if ($message): ?>
                    <div class="alert alert-<?php echo $messageType; ?>">
                        <?php echo $message; ?>
                        <?php if ($newMaterialId): ?>
                            <br><strong>Generated Material ID: <?php echo $newMaterialId; ?></strong>
                        <?php endif; ?>
                    </div>
                <?php endif; ?>
                
                <!-- Insert Form -->
                <form method="POST" action="" data-validate>
                    <div class="form-row">
                        <div class="form-group">
                            <label for="material_name" class="required">Material Name</label>
                            <input type="text" name="material_name" id="material_name" 
                                   class="form-control"
                                   required
                                   minlength="2"
                                   maxlength="100"
                                   value="<?php echo htmlspecialchars($_POST['material_name'] ?? ''); ?>"
                                   placeholder="e.g., Solid Oak Wood, Leather, Cotton Fabric">
                            <div class="invalid-feedback" id="material_name_error"></div>
                        </div>
                        
                        <div class="form-group">
                            <label for="unit" class="required">Unit</label>
                            <input type="text" name="unit" id="unit" 
                                   class="form-control"
                                   required
                                   maxlength="20"
                                   value="<?php echo htmlspecialchars($_POST['unit'] ?? ''); ?>"
                                   placeholder="e.g., Board Feet, Square Meters, Pieces">
                            <div class="invalid-feedback" id="unit_error"></div>
                        </div>
                    </div>
                    
                    <div class="form-row">
                        <div class="form-group">
                            <label for="physical_quantity" class="required">Physical Quantity</label>
                            <input type="number" name="physical_quantity" id="physical_quantity" 
                                   class="form-control"
                                   data-type="number"
                                   required
                                   min="0.01"
                                   step="0.01"
                                   value="<?php echo htmlspecialchars($_POST['physical_quantity'] ?? ''); ?>"
                                   placeholder="Initial stock quantity">
                            <div class="invalid-feedback" id="physical_quantity_error"></div>
                        </div>
                        
                        <div class="form-group">
                            <label for="reorder_level">Reorder Level</label>
                            <input type="number" name="reorder_level" id="reorder_level" 
                                   class="form-control"
                                   data-type="number"
                                   min="0"
                                   step="0.01"
                                   value="<?php echo htmlspecialchars($_POST['reorder_level'] ?? '0'); ?>"
                                   placeholder="Alert when quantity falls below this level">
                            <div class="invalid-feedback" id="reorder_level_error"></div>
                            <small>You will be alerted when stock falls below this level</small>
                        </div>
                    </div>
                    
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">➕ Add Material</button>
                        <button type="reset" class="btn btn-secondary">Clear Form</button>
                    </div>
                </form>
                
                <hr style="margin: var(--spacing-xl) 0;">
                
                <!-- Existing Materials List -->
                <h3>Existing Materials</h3>
                <?php if (empty($materials)): ?>
                    <div class="alert alert-info">No materials found. Add your first material above.</div>
                <?php else: ?>
                    <div class="table-container">
                        <table data-sortable>
                            <thead>
                                <tr>
                                    <th class="sortable">Material ID</th>
                                    <th class="sortable">Material Name</th>
                                    <th class="sortable">Quantity</th>
                                    <th class="sortable">Unit</th>
                                    <th class="sortable">Reorder Level</th>
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($materials as $material): ?>
                                    <tr>
                                        <td><?php echo $material['MaterialID']; ?></td>
                                        <td><?php echo htmlspecialchars($material['MaterialName']); ?></td>
                                        <td><?php echo number_format($material['PhysicalQuantity'], 2); ?></td>
                                        <td><?php echo htmlspecialchars($material['Unit']); ?></td>
                                        <td><?php echo number_format($material['ReorderLevel'], 2); ?></td>
                                        <td>
                                            <?php if ($material['PhysicalQuantity'] <= $material['ReorderLevel'] && $material['ReorderLevel'] > 0): ?>
                                                <span class="badge badge-danger">Low Stock!</span>
                                            <?php elseif ($material['PhysicalQuantity'] > 0): ?>
                                                <span class="badge badge-success">In Stock</span>
                                            <?php else: ?>
                                                <span class="badge badge-secondary">Out of Stock</span>
                                            <?php endif; ?>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                <?php endif; ?>
            </main>
        </div>
    </div>

    <footer class="footer">
        <div class="container">
            <p>&copy; 2025 Premium Living Furniture Co. Ltd. All rights reserved.</p>
        </div>
    </footer>

    <script src="../assets/js/validation.js"></script>
</body>
</html>